"use client";
import { create } from "zustand";
import { persist } from "zustand/middleware";
import { useHydrated } from "@/lib/hooks";
import { notifications } from "@/mock/account";
import { useDemo } from "@/store/demo";
import { Button } from "@/components/ui/Button";
const usePrefs=create<{read:string[]; channels:Record<string,boolean>; mark:(ids:string[])=>void; toggle:(key:string)=>void}>()(persist((set)=>({read:[],channels:{"Sifariş e-poçtları":true,"Servis e-poçtları":true,"Marketinq":false,"SMS":false},mark:ids=>set(s=>({read:[...new Set([...s.read,...ids])]})),toggle:key=>set(s=>({channels:{...s.channels,[key]:!s.channels[key]}}))}),{name:"ep-notifications-v1"}));
export function NotificationSettings(){const prefs=usePrefs();const hydrated=useHydrated();const records=useDemo(s=>s.records);if(!hydrated)return null;const items=[...records.map(r=>({id:r.id,title:`${r.title}: ${r.status}`,body:r.id,date:r.date})),...notifications];return <section className="space-y-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-semibold">Bildirişlər</h2><Button variant="secondary" size="sm" onClick={()=>prefs.mark(items.map(i=>i.id))}>Hamısını oxunmuş et</Button></div>{items.map(n=><button key={n.id} onClick={()=>prefs.mark([n.id])} className={`block w-full border p-4 text-left ${prefs.read.includes(n.id)?"bg-paper":"bg-brass-50"}`}><span className="block font-medium">{n.title}</span><span className="mt-1 block text-sm text-stone">{n.body}</span><span className="mt-2 block text-xs">{prefs.read.includes(n.id)?"Oxunub":"Yeni"}</span></button>)}<div className="space-y-3 border p-5"><h3 className="font-semibold">Bildiriş seçimləri</h3>{Object.entries(prefs.channels).map(([key,enabled])=><label key={key} className="flex min-h-11 justify-between gap-3 border-b py-2">{key}<input type="checkbox" checked={enabled} onChange={()=>prefs.toggle(key)}/></label>)}<p className="text-xs text-stone">Seçimlər bu brauzerdə saxlanılır. Demo bildiriş göndərmir.</p></div></section>}
