"use client";
import { useState } from "react";
import { useDemo } from "@/store/demo";
import { DemoActivity } from "./DemoActivity";
import { Button } from "@/components/ui/Button";
export function TechnicianDemo({locale}: {locale:string}) {
 const add=useDemo(s=>s.add); const [note,setNote]=useState(""); const [parts,setParts]=useState(""); const [saved,setSaved]=useState(false);
 return <div className="container-page max-w-5xl py-10"><p className="text-xs uppercase tracking-widest text-brass-600">Usta kabineti · Demo</p><h1 className="my-4 text-3xl font-semibold">İşlərim və servis qeydləri</h1><p className="mb-6 text-stone">Müraciəti qəbul edin, statusunu yeniləyin və görülmüş işi qeyd edin.</p><Button onClick={()=>add({id:`REP-${crypto.randomUUID().slice(0,8).toUpperCase()}`,kind:"repairs",title:"Menteşə tənzimlənməsi",detail:"Nümunə iş · Yasamal · 10:00–12:00",technician:"Əli Məmmədov"})}>Nümunə iş əlavə et</Button><div className="mt-6"><DemoActivity section="all" locale={locale} manage/></div><form className="space-y-4 border bg-bone p-5" onSubmit={e=>{e.preventDefault();add({id:`SRV-${crypto.randomUUID().slice(0,8).toUpperCase()}`,kind:"repairs",title:"Servis tamamlama qeydi",detail:`Görülən iş: ${note}\nİstifadə olunan hissələr: ${parts}`,technician:"Əli Məmmədov"});setSaved(true);}}><h2 className="text-xl font-semibold">İşin tamamlanması</h2><label className="block text-sm">Diaqnostika və görülən iş<textarea required minLength={10} value={note} onChange={e=>setNote(e.target.value)} className="mt-2 min-h-28 w-full border p-3"/></label><label className="block text-sm">İstifadə edilən hissələr<input required value={parts} onChange={e=>setParts(e.target.value)} className="mt-2 w-full border p-3"/></label><label className="flex gap-2 text-sm"><input required type="checkbox"/>Müştəri işi qəbul etdi (demo)</label><Button type="submit">Servis qeydini saxla</Button>{saved&&<p role="status" className="text-success">Servis tarixçəsinə əlavə edildi.</p>}</form></div>;
}
