import Link from "next/link";
const groups = [
 {title:"Qapı seçimi", text:"Kataloqdan başlayın, modelləri müqayisə edin və öz qapınızı yaradın.",links:[["Kataloq və filtrlər","qapilar"],["Konfiqurator","konfiqurator"],["Müqayisə","muqayise"],["Favorilər","favoritler"]]},
 {title:"Sifariş və xidmət",text:"Demo müraciət yaradın. Nəticə eyni brauzerdə hesabda və idarəetmə panelində görünəcək.",links:[["Səbət və sifariş","sebet"],["Qiymət təklifi","quote"],["Ölçü sifarişi","olcu"],["Təmir müraciəti","temir"]]},
 {title:"Müştəri kabineti",text:"Saxlanmış dizaynlar, sifariş tarixçəsi və satışdan sonrakı xidmətlər.",links:[["Giriş / qeydiyyat","giris"],["Sifarişlər","hesab/orders"],["Dizaynlarım","hesab/configurations"],["Zəmanətlər","hesab/warranties"],["Ünvanlar","hesab/addresses"]]},
 {title:"Komandanın işi",text:"Sifariş və təmirin idarəsi, usta təyinatı, kataloq və məzmun redaktəsi.",links:[["Admin paneli","admin"],["Məhsul idarəsi","admin/products"],["Servis idarəsi","admin/repairs"],["Usta kabineti","usta"],["Stok","admin/inventory"]]},
 {title:"Məzmun və portfolio",text:"Müştəriyə seçim etmək üçün lazım olan məlumat və nümunələr.",links:[["Layihələr və əvvəl/sonra","layiheler"],["Brendlər","brands"],["Bloq","blog"],["Suallar və cavablar","faq"],["Əlaqə","elaqe"]]}
];
export const metadata={title:"Platformanın imkanları — demo",robots:{index:false,follow:false}};
export default async function Page({params}: {params:Promise<{locale:string}>}) {const {locale}=await params;return <div className="container-page py-12"><p className="text-xs uppercase tracking-widest text-brass-600">İnteraktiv təqdimat</p><h1 className="my-4 max-w-3xl text-4xl font-semibold tracking-tight">Qapı seçimindən ömürlük servisə qədər.</h1><p className="mb-10 max-w-2xl text-stone">Bu təqdimatda platformanın ekranlarını və əsas axınlarını sınaqdan keçirə bilərsiniz. Məlumatlar yalnız brauzerinizdə saxlanılır.</p><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{groups.map((g,i)=><section key={g.title} className="border bg-bone p-6"><span className="text-sm text-brass-600">0{i+1}</span><h2 className="my-3 text-xl font-semibold">{g.title}</h2><p className="mb-5 text-sm leading-relaxed text-stone">{g.text}</p><ul className="space-y-3">{g.links.map(([label,path])=><li key={path}><Link className="flex justify-between border-t pt-3 text-sm hover:text-brass-600" href={`/${locale}/${path}`}>{label}<span>→</span></Link></li>)}</ul></section>)}<section className="border bg-ink p-6 text-white"><p className="text-sm text-brass-300">Növbəti mərhələ</p><h2 className="my-3 text-xl font-semibold">Canlı inteqrasiyalar</h2><p className="text-sm leading-relaxed text-white/70">Real hesab, onlayn ödəniş, SMS/e-poçt, məlumat bazası və fayl saxlama backend mərhələsində qoşulacaq. AI məsləhətçisi, 3D və AR ayrıca gələcək mərhələdir.</p></section></div></div>;}
